### ISSUE TITLE
RRD Step is wrong with Interval Length set in seconds

### ISSUE THREAD

**Issue by ludovicgrondin** [centreon/centreon-broker#89] opened 2017-03-14 03:32 UTC
Hello,

I changed my "Interval Length" in the page "Administration --> Parameters --> Monitoring" from 60 seconds to 1 second.
In my service configuration, I define a "normal check interval" to 300.

My service is now checked every 5 minutes (300 seconds) but my graph as a new point every 5 hours.

When I use rrdtool command on a curve, I have a step of 18000 (it must be 300) .

# rrdtool info /var/lib/centreon/metrics/3712.rrd
filename = "/var/lib/centreon/metrics/3712.rrd"
rrd_version = "0003"
step = 18000
last_update = 1489459988
header_size = 792
ds[value].index = 0
ds[value].type = "GAUGE"
ds[value].minimal_heartbeat = 180000
ds[value].min = NaN
ds[value].max = NaN
ds[value].last_ds = "0.000000"
ds[value].value = 0,0000000000e+00
ds[value].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 51841
rra[0].cur_row = 8754
rra[0].pdp_per_row = 1
rra[0].xff = 5,0000000000e-01
rra[0].cdp_prep[0].value = NaN
rra[0].cdp_prep[0].unknown_datapoints = 0
rra[1].cf = "AVERAGE"
rra[1].rows = 4321
rra[1].cur_row = 1877
rra[1].pdp_per_row = 12
rra[1].xff = 5,0000000000e-01
rra[1].cdp_prep[0].value = 0,0000000000e+00
rra[1].cdp_prep[0].unknown_datapoints = 0

Centreon-broker 3.0.3
Centreon 2.8.3

regards,

**Comment by snk33** [comment] 2017-04-28 09:40
Hello,

I've got the same issue, it seems to have appeared after auto-updating from 2.11.5 to 3.0.3. RRD step is 60 times higher than it should when monitoring interval is set to 1s instead of 60s.

I'm doing some tests on a CPU Load graph with an expected 15s step, older graphs were well generated but new ones comes with a 900 step.
Trying to put check interval on service level instead of service template doesn't change anything so it doesn't look like a templating issue.

I tried to search in source code to see what could be related but I can't find anything related to this, the only change made could be rrd/src/creator.cc on line 124 but it's been made a year ago so centreon-broker 2.11.5 would have been affected too.

It would be great to solve this, it doesn't only avoid us to graph more than every 60s but our CPU graph are generated every 900s / 15 min so they're becoming pretty useless...

Regards.

**Comment by ganoze** [comment] 2017-07-24 14:51
I took a look at this issue and confirmed it. The problem is located in Centreon Web which does not properly export centreon/centreon#5461.

**Comment by snk33** [comment] 2017-09-22 10:41
Hello,

I've made some tests but it still really wrong.

My example is a graph on a check made every 60s (with monitoring engine set to 1s). Before the update, RRD step was set to 3600, now it's 1 (instead of 60, according to the interval check).

Looking into rrdtool info, this changes made :
step : 3600 -> 1
rra[0].pdp_per_row : 1 -> 3600

If I take an older graph which has a good scale (a point every minute) :
step = 60
rra[0].pdp_per_row = 1
rra[1].pdp_per_row = 12

By the way, the .rrd newly created just had 1 RRA instead of 2 before this patch, is it normal ?

Hope you'll find out how to fix this, graphs are quite useless since january now :(

**Comment by ganoze** [comment] 2017-10-05 07:56
Do you have the latest release of Centreon Web 2.8 ? If you have, please export your configuration to your pollers and try to rebuild your graphs. With your configuration values you should still have two RRA but with a one second step.

Let me know if that works out.

**Comment by snk33** [comment] 2017-10-05 08:20
Yes, to be sure I've just made a test after updating to the latest version (2.8.14), exported configurations with a complete restart of engine (+ the whole server), tried to rebuild RRD DB and it's the same.

Before rebuild :
filename = "/var/lib/centreon/metrics/4600.rrd"
rrd_version = "0003"
step = 1
last_update = 1507190787
header_size = 584
ds[value].index = 0
ds[value].type = "GAUGE"
ds[value].minimal_heartbeat = 36000
ds[value].min = NaN
ds[value].max = NaN
ds[value].last_ds = "5.000000"
ds[value].value = 0,0000000000e+00
ds[value].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 8761
rra[0].cur_row = 4499
rra[0].pdp_per_row = 3600
rra[0].xff = 5,0000000000e-01
rra[0].cdp_prep[0].value = 2,0430000000e+03
rra[0].cdp_prep[0].unknown_datapoints = 0

After rebuild :
filename = "/var/lib/centreon/metrics/4600.rrd"
rrd_version = "0003"
step = 1
last_update = 1507191348
header_size = 584
ds[value].index = 0
ds[value].type = "GAUGE"
ds[value].minimal_heartbeat = 36000
ds[value].min = NaN
ds[value].max = NaN
ds[value].last_ds = "5.000000"
ds[value].value = 0,0000000000e+00
ds[value].unknown_sec = 0
rra[0].cf = "AVERAGE"
rra[0].rows = 8761
rra[0].cur_row = 2557
rra[0].pdp_per_row = 3600
rra[0].xff = 5,0000000000e-01
rra[0].cdp_prep[0].value = 4,8480000000e+03
rra[0].cdp_prep[0].unknown_datapoints = 0

I also tried to manually delete the .rrd file to force the rebuild but it leads to the same result.

**Comment by ganoze** [comment] 2017-10-05 08:46
Can you check that the values defined in Administration -> Parameters -> Monitoring -> Interval Length is the same than the one defined in the <interval> tag in /etc/centreon-broker/central-broker.xml ?

**Comment by snk33** [comment] 2017-10-05 08:57
Yes, both settings are set to a 1 (s).

By the way this is a single-server CES installation (web, engine, broker on the same server) but we have the same issue on another installation with web and brokers separated.

**Comment by ganoze** [comment] 2017-10-05 11:52
Seems like there is another bug in Centreon Broker that prevents graph to be correctly rebuilt using an interval length that is not set to 60.

https://github.com/centreon/centreon-broker/blob/4ca684a89690bdc28eec99fea556677a6900888d/storage/src/rebuilder.cc#L146

**Comment by ganoze** [comment] 2017-10-06 08:11
Should be fixed in PR #133

**Comment by snk33** [comment] 2017-10-06 08:18
Thanks a lot, I will do some tests when centreon-broker 3.0.11 will come out :)

**Comment by snk33** [comment] 2017-11-20 11:59
Hello,

I've done some testings on CB 3.0.11.

Rebuilded graph with 60s normal check interval (1s monitoring interval) :
step = 1
rra[0].pdp_per_row = 60
rra[1].pdp_per_row = 3600

Rebuilded graph with 15s normal check interval (1s monitoring interval) :
step = 1
rra[0].pdp_per_row = 15
rra[1].pdp_per_row = 3600

Do you confirm that the following graph for a 60s normal check interval ain't good :
step = 60
rra[0].pdp_per_row = 1
rra[1].pdp_per_row = 12

I don't have much datas because of 1 day MySQL retention but it seems to be ok. If you have any tool or function that could be helpful to keep datas from RRD when rebuilding, feel free to share ;-)

**Comment by larkoie** [comment] 2017-12-19 08:25
Hi,

I'm facing the same issue. I migrated on a new server from Nagios to full centreon : 
Centreon Broker 3.0.11
Centreon Engine 1.8.1
Centreon 2.8.16

On my old Nagios + Centreon, graphs are working and .rrd files are fine. On the new centreon graphs shows some points here and there during 10/20 minutes after a restart of the services but then nothing and the .rrd files are full of "NaN" instead of the values.
Normal check interval is set to 60 sec (1*60) in centreon web for each service. When we look at the .rrd files, the old one (nagios server) show 60sec step but the new one(centreon) shows 1sec step. I also noticed that on the old one the name of the metric is correctly retrived (ie : CPU) but in the new one it just says "Value". Please find the .rrd files info below : 

 Old server (nagios): 
_<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rrd SYSTEM "http://oss.oetiker.ch/rrdtool/rrdtool.dtd">

<rrd>
        <version>0003</version>
        <step>60</step> 
        <lastupdate>1511945338</lastupdate> 

        <ds>
                <name> CPU </name>
                <type> GAUGE </type>
                <minimal_heartbeat>86400</minimal_heartbeat>
                <min>NaN</min>
                <max>NaN</max>

                
                <last_ds>1.000000e+02</last_ds>
                <value>5.8000000000e+03</value>
                <unknown_sec> 0 </unknown_sec>
        </ds>

        
        <rra>
                <cf>AVERAGE</cf>
                <pdp_per_row>1</pdp_per_row> 

                <params>
                <xff>5.0000000000e-01</xff>
                </params>
                <cdp_prep>
                        <ds>
                        <primary_value>1.0000000000e+02</primary_value>
                        <secondary_value>1.0000000000e+02</secondary_value>
                        <value>NaN</value>
                        <unknown_datapoints>0</unknown_datapoints>
                        </ds>
                </cdp_prep>
                <database>_

New server (centreon) : 
_<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rrd SYSTEM "http://oss.oetiker.ch/rrdtool/rrdtool.dtd">

<rrd>
        <version>0003</version>
        <step>1</step> 
        <lastupdate>1513611274</lastupdate> 

        <ds>
                <name> value </name>
                <type> GAUGE </type>
                <minimal_heartbeat>600</minimal_heartbeat>
                <min>NaN</min>
                <max>NaN</max>

                
                <last_ds>59.400000</last_ds>
                <value>0.0000000000e+00</value>
                <unknown_sec> 0 </unknown_sec>
        </ds>

        
        <rra>
                <cf>AVERAGE</cf>
                <pdp_per_row>60</pdp_per_row> 

                <params>
                <xff>5.0000000000e-01</xff>
                </params>
                <cdp_prep>
                        <ds>
                        <primary_value>NaN</primary_value>
                        <secondary_value>5.9400000000e+01</secondary_value>
                        <value>2.0196000000e+03</value>
                        <unknown_datapoints>0</unknown_datapoints>
                        </ds>
                </cdp_prep>
                <database>
                         <row><v>NaN</v></row>
                         <row><v>NaN</v></row>_

I have the same config on my new test server and prod server and they have the same behaviour so my guess is that there is an issue somewhere in the Centreon version i'm using. I worked on this for a week but could not find anything.

Thanks.

**Comment by ganoze** [comment] 2018-03-28 12:17
@snk33 Your last RRD file was likely generated with an older version of Centreon Broker where we used this kind of RRA.

@larkoie Indeed we changed the RRA layout within RRD files. The step is now always of 1 seconds and aggregation is based on check interval. If you do not have correct values in your RRD files I would be interested in getting an impacted RRD file along with the version of rrdtool you are using.

**Closed** 2022-06-06 13:51 UTC
Labels: Kind/Bug, Status/Implemented
