### ISSUE TITLE
Centreon Broker 3.0.3 failing with TLS 

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon-broker#90] opened 2017-03-29 10:16 UTC
Hi All,

We have a strange issue with centreon broker 3.0.3.  If we are using TLS, the centreon broker is fail in1-2 hours and cannot communicate with pollers.
The cert files have the proper permissions,owner,etc.

Centreon Version: 2.8.4
Centreon Broker Version: 3.0.3

Here is our log file:
/var/log/centreon-broker/central-broker-master.log
**With TLS:**
 Config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[1490717897] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490717927] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490717957] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490717987] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718017] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718047] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718077] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718107] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718137] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718167] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718197] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718227] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718257] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718287] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718317] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718347] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718377] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718407] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718437] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718461] error:   stats: FIFO thread will exit due to the following error: cannot open FIFO file: Too many open files
[1490718467] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TCP peer ':0' is disconnected
[1490718497] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718527] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718557] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718587] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718617] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718647] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718677] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718707] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718737] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718760] error:   storage: rebuilder: could not connect to Centreon Storage database: could not open database: Unknown MySQL server host 'global_nagios_sql_primary' (24) QMYSQL: Unable to connect
[1490718767] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718797] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718827] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718857] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718887] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718917] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718947] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490718977] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490719007] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.
[1490719037] error:   acceptor: endpoint 'central-broker-master-input' could not accept client: TLS: could not load certificate: Error while reading file.

**Without TLS: -- no error**
Centreon Broker 3.0.3 log file closed
Centreon Broker 3.0.3 log file opened
[1490777895] config:  module applier: loading directory '/usr/share/centreon/lib/centreon-broker'
[root@chic100ipngc1 centreon-broker]#

Can you investigate this issue?
What should cause it?

Regards,

Tamas

**Comment by ganoze** [comment] 2017-04-05 12:31
Seems like a duplicate of #33 .

**Closed by ganoze** 2017-04-05 12:31 UTC
Labels: Kind/Bug
