### ISSUE TITLE
[3.0.7] Too much perfdata files in the queue

### ISSUE THREAD

**Issue by Tomszy** [centreon/centreon-broker#109] opened 2017-06-21 19:40 UTC
**Centreon Web version**:2.8.8
**Centreon Engine version**:1.7.2
**Centreon Broker version**:3.0.7
**OS**: Oracle Linux 7
**Additional environment details** :Virtual

**Steps to reproduce the issue:** 
We have 220000 checks in centreon. And the broker cannot handle the perdata as we see.
Screenshot:
![image](https://user-images.githubusercontent.com/25457811/27403073-5d7e7e2e-56c9-11e7-8c65-e604356a4db0.png)

We have dedicated broker server with 32 GB RAM and 4 core CPU.
We have tried to change the event que max size to 200000 from 50000 but it not helped.
Here is our broker-master.xml file:

```
<?xml version="1.0" encoding="UTF-8"?>
<centreonBroker>
 <broker_id><![CDATA[1]]></broker_id>
 <broker_name><![CDATA[central-broker-master]]></broker_name>
 <poller_id><![CDATA[1]]></poller_id>
 <poller_name><![CDATA[Central]]></poller_name>
 <module_directory><![CDATA[/usr/share/centreon/lib/centreon-broker]]></module_directory>
 <log_timestamp><![CDATA[1]]></log_timestamp>
 <log_thread_id><![CDATA[0]]></log_thread_id>
 <event_queue_max_size><![CDATA[50000]]></event_queue_max_size>
 <command_file><![CDATA[/var/centreon_failover/command.sock]]></command_file>
 <cache_directory><![CDATA[/var/centreon_failover]]></cache_directory>
 <input>
  <name><![CDATA[central-broker-master-input]]></name>
  <port><![CDATA[5669]]></port>
  <retry_interval><![CDATA[60]]></retry_interval>
  <buffering_timeout><![CDATA[0]]></buffering_timeout>
  <protocol><![CDATA[bbdo]]></protocol>
  <tls><![CDATA[auto]]></tls>
  <negotiation><![CDATA[yes]]></negotiation>
  <one_peer_retention_mode><![CDATA[no]]></one_peer_retention_mode>
  <compression><![CDATA[auto]]></compression>
  <type><![CDATA[ipv4]]></type>
 </input>
 <logger>
  <name><![CDATA[/var/log/centreon-broker/central-broker-master.log]]></name>
  <config><![CDATA[yes]]></config>
  <debug><![CDATA[no]]></debug>
  <error><![CDATA[yes]]></error>
  <info><![CDATA[no]]></info>
  <level><![CDATA[low]]></level>
  <type><![CDATA[file]]></type>
 </logger>
 <output>
  <name><![CDATA[central-broker-master-sql]]></name>
  <db_type><![CDATA[mysql]]></db_type>
  <failover><![CDATA[central-broker-master-sql-failover]]></failover>
  <retry_interval><![CDATA[60]]></retry_interval>
  <buffering_timeout><![CDATA[0]]></buffering_timeout>
  <db_host><![CDATA[global_nagios_sql_primary]]></db_host>
  <db_port><![CDATA[3306]]></db_port>
  <db_user><![CDATA[centreon]]></db_user>
  <db_password><![CDATA[centreon]]></db_password>
  <db_name><![CDATA[centreon_storage]]></db_name>
  <queries_per_transaction><![CDATA[40000]]></queries_per_transaction>
  <check_replication><![CDATA[no]]></check_replication>
  <read_timeout><![CDATA[10]]></read_timeout>
  <filters>
   <category><![CDATA[correlation]]></category>
   <category><![CDATA[neb]]></category>
  </filters>
  <type><![CDATA[sql]]></type>
 </output>
 <output>
  <name><![CDATA[centreon-broker-master-rrd]]></name>
  <port><![CDATA[5670]]></port>
  <host><![CDATA[localhost]]></host>
  <failover><![CDATA[centreon-broker-master-rrd-failover]]></failover>
  <retry_interval><![CDATA[60]]></retry_interval>
  <buffering_timeout><![CDATA[0]]></buffering_timeout>
  <protocol><![CDATA[bbdo]]></protocol>
  <tls><![CDATA[auto]]></tls>
  <negotiation><![CDATA[yes]]></negotiation>
  <one_peer_retention_mode><![CDATA[no]]></one_peer_retention_mode>
  <filters>
   <category><![CDATA[storage]]></category>
  </filters>
  <compression><![CDATA[no]]></compression>
  <type><![CDATA[ipv4]]></type>
 </output>
 <output>
  <name><![CDATA[central-broker-master-perfdata]]></name>
  <interval><![CDATA[60]]></interval>
  <length><![CDATA[15552000]]></length>
  <failover><![CDATA[central-broker-master-perfdata-failover]]></failover>
  <buffering_timeout><![CDATA[0]]></buffering_timeout>
  <retry_interval><![CDATA[60]]></retry_interval>
  <db_type><![CDATA[mysql]]></db_type>
  <db_host><![CDATA[global_nagios_sql_primary]]></db_host>
  <db_port><![CDATA[3306]]></db_port>
  <db_user><![CDATA[centreon]]></db_user>
  <db_password><![CDATA[xxxxxx]]></db_password>
  <db_name><![CDATA[centreon_storage]]></db_name>
  <queries_per_transaction><![CDATA[50000]]></queries_per_transaction>
  <read_timeout><![CDATA[10]]></read_timeout>
  <check_replication><![CDATA[no]]></check_replication>
  <rebuild_check_interval><![CDATA[300]]></rebuild_check_interval>
  <store_in_data_bin><![CDATA[yes]]></store_in_data_bin>
  <insert_in_index_data><![CDATA[1]]></insert_in_index_data>
  <filters>
   <category><![CDATA[neb]]></category>
  </filters>
  <type><![CDATA[storage]]></type>
 </output>
 <output>
  <name><![CDATA[central-broker-master-sql-failover]]></name>
  <path><![CDATA[/var/centreon_failover/central-broker-master-sql.retention]]></path>
  <protocol><![CDATA[bbdo]]></protocol>
  <max_size><![CDATA[500000000]]></max_size>
  <compression><![CDATA[no]]></compression>
  <type><![CDATA[file]]></type>
 </output>
 <output>
  <name><![CDATA[centreon-broker-master-rrd-failover]]></name>
  <path><![CDATA[/var/centreon_failover/centreon-broker-master-rrd.retention]]></path>
  <protocol><![CDATA[bbdo]]></protocol>
  <max_size><![CDATA[500000000]]></max_size>
  <compression><![CDATA[no]]></compression>
  <type><![CDATA[file]]></type>
 </output>
 <output>
  <name><![CDATA[central-broker-master-perfdata-failover]]></name>
  <path><![CDATA[/var/centreon_failover/central-broker-master-perfdata.retention]]></path>
  <protocol><![CDATA[bbdo]]></protocol>
  <max_size><![CDATA[500000000]]></max_size>
  <compression><![CDATA[no]]></compression>
  <type><![CDATA[file]]></type>
 </output>
 <stats>
  <type><![CDATA[stats]]></type>
  <name><![CDATA[central-broker-master-stats]]></name>
  <json_fifo><![CDATA[/var/centreon_failover/central-broker-master-stats.json]]></json_fifo>
 </stats>
</centreonBroker>

```

**Describe the results you expected:**
We expect less perfdata file.

I hope you can help us! Maybe some tuning is missing or something like that? Or is this a bug?

Thanks,

Tamas

**Comment by Sims24** [comment] 2017-06-22 06:20
Hello, 

Could you also provide the json stats file for the Central-broker ? 

You may need to setup à second broker listening on an other port to be able to handle datas on realtime.

**Comment by zskarman** [comment] 2017-06-22 10:27
Hi,

I've checked the json and i cannot copy, also there is no any content in there.
Could you please send us an sample to setup the 2nd broker?

But i have in that time one question, we already get 2 machines for broker, cause 220.000 checks here, and the multiple broker could not update the metrics table because it's locked each other, and stopped.
So what i see in one time one broker could update the metrics.

But if you have any solution please let me know.

Rgs, Zsolt

**Comment by Sims24** [comment] 2017-06-22 10:43
Please copy paste result of :

**Comment by zskarman** [comment] 2017-06-23 07:30
![image](https://user-images.githubusercontent.com/24320218/27471010-886e671a-57f6-11e7-8af8-9b899d44db45.png)

**Comment by zskarman** [comment] 2017-06-23 07:39
This is the json output. right now it works, if i changed the interval for the checks, but this is an workaround.
we need to keep the previous intervals for the checks.

Rgs, Zsolt

{
    "compiled with qt": "4.8.5",
    "endpoint central-module-master-output": {
        "bbdo_input_ack_limit": "1000",
        "bbdo_unacknowledged_events": "0",
        "event_processing_speed": "0.266667",
        "failover": {
            "event_processing_speed": "0",
            "failover": {},
            "last_connection_attempt": "-1",
            "last_connection_success": "-1",
            "last_event_at": "-1",
            "queue_file_enabled": "no",
            "queued_events": "716",
            "read_filters": "all",
            "state": "connecting",
            "status": "",
            "unacknowledged_events": "716",
            "write_filters": "all"
        },
        "last_connection_attempt": "1498097428",
        "last_connection_success": "1498097428",
        "last_event_at": "1498203190",
        "memory_file_path": "/var/centreon_failover//central-module-master.memory.central-module-master-output",
        "queue_file_enabled": "no",
        "queue_file_path": "/var/centreon_failover//central-module-master.queue.central-module-master-output",
        "queued_events": "716",
        "read_filters": "all",
        "state": "connected",
        "status": "reading event from multiplexing engine",
        "unacknowledged_events": "716",
        "write_filters": "all"
    },
    "module /usr/share/centreon/lib/centreon-broker/05-dumper.so": {
        "size": "467016B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/10-neb.so": {
        "size": "721824B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/15-stats.so": {
        "size": "99112B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/20-bam.so": {
        "size": "1279008B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/20-storage.so": {
        "size": "243648B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/30-correlation.so": {
        "size": "222512B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/40-notification.so": {
        "size": "623296B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/50-tcp.so": {
        "size": "74072B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/60-tls.so": {
        "size": "73792B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/70-rrd.so": {
        "size": "124040B",
        "state": "loaded"
    },
    "module /usr/share/centreon/lib/centreon-broker/80-sql.so": {
        "size": "156768B",
        "state": "loaded"
    },
    "now": "1498203190",
    "pid": "15328",
    "running with qt": "4.8.5",
    "version": "3.0.7"
}

**Comment by julienmathis** [comment] 2017-06-23 07:51
How much was your previous check interval ?

**Comment by zskarman** [comment] 2017-06-23 07:55
Hi,

We have approx 220.000 checks some are [10-20 checks] applied on all host [11000], like with 15 mins interval.
means, 11.000 checks x 15 tests x every 15 minutes.

in the previous version has this: https://github.com/centreon/centreon/issues/5369

**Comment by Sims24** [comment] 2017-06-23 08:07
I'm prelly sure this option has no effect in an engine/broker setup. 

You have to manage this with "insert_into_data_bin" option in your broker configuration to make it global, or use Administration > Options > Performances to disable graph for a specific service I guess.

Also I think your problem is more related to https://github.com/centreon/centreon-broker/issues/95 then we had some performance degradation on this point .. what do you think @ganoze @julienmathis  ?

**Comment by zskarman** [comment] 2017-06-23 08:10
Hi,
The disable graph per service on the template should solved this but not available on 2.8.8 centreon/centreon#5369

**Comment by julienmathis** [comment] 2017-06-23 13:30
Can we have specification of your MySQL/MariaDB server ?

**Comment by zskarman** [comment] 2017-06-26 08:43
Do you use rrdcached ? - YES

Mysql Config: [SUN hardware 256 GB more than 56 CPU]



[client]
default-character-set          = utf8
port                           = 3306
socket                         = /var/run/mysql/mysqld.sock

[mysql]
default-character-set          = utf8

[mysqld_safe]
socket                         = /var/run/mysql/mysqld.sock
nice                           = 0
open-files-limit               = 8192

[mysqld]
user                           = mysql
pid-file                       = /var/run/mysql/mysqld.pid
socket                         = /var/run/mysql/mysqld.sock
port                           = 3306
datadir                        = /var/lib/mysql
tmpdir                         = /tmp
log-error                      = /var/log/mysql/error.log
!includedir /etc/mysql/conf.d
collation-server               = utf8_general_ci
character-set-server           = utf8

plugin-load=audit_log.so
audit-log=FORCE_PLUS_PERMANENT
audit_log_strategy=ASYNCHRONOUS
audit_log_rotate_on_size=500M


skip-external-locking
local-infile=0
skip-grant-tables=FALSE
skip_symbolic_links=YES
sql_mode=NO_ENGINE_SUBSTITUTION
open_files_limit = 32000
secure_auth=ON

# * Fine Tuning
# #

key_buffer_size              = 16M
max_allowed_packet=1024M
thread_stack            = 192K
thread_cache_size       = 64

# This replaces the startup script and checks MyISAM tables if needed
# the first time they are touched

myisam-recover-options
max_connections        = 1000
#table_cache            = 64
thread_concurrency     = 8

#
# * Query Cache Configuration
#

query_cache_limit       = 4M
query_cache_size        = 128M

#Log setup for long running queries
long_query_time = 5

#Custom settings for Replication
back_log = 50
max_connect_errors = 10
table_open_cache = 2048
binlog_cache_size = 1M
max_heap_table_size = 16M
sort_buffer_size = 8M
join_buffer_size = 8M
ft_min_word_len = 4
default-storage-engine = InnoDB
transaction_isolation = READ-COMMITTED
tmp_table_size = 16M
binlog_format=mixed
slow_query_log
sync_binlog = 1
key_buffer_size = 32M
read_buffer_size = 2M
read_rnd_buffer_size = 16M
bulk_insert_buffer_size = 64M
group_concat_max_len = 4096
expire_logs_days = 8
lower_case_table_names = 1

# ISAM settings
myisam_sort_buffer_size = 128M
myisam_max_sort_file_size = 10G
myisam_repair_threads = 1

#InnoDB setup
innodb_flush_log_at_trx_commit=1

#innodb_flush_method = O_DSYNC
innodb_additional_mem_pool_size = 16M
innodb_buffer_pool_size = 100G
innodb_data_file_path = ibdata1:100M:autoextend
innodb_file_io_threads = 4
innodb_thread_concurrency = 8
innodb_fast_shutdown = 2
innodb_log_buffer_size = 8M
innodb_log_file_size = 256M
innodb_log_files_in_group = 3
innodb_max_dirty_pages_pct = 90
innodb_lock_wait_timeout = 120
innodb_file_per_table = 1

## Replication Settings
server-id=45141
log-bin = /var/log/mysql/bin/master/mysql-bin.log
relay-log = /var/log/mysql/bin/slave/mysql-relay-bin.log
auto_increment_increment=4
auto_increment_offset=1
log_slave_updates = ON
expire_logs_days=10
max_binlog_size=500M
binlog_format            = MIXED
binlog_row_image         = minimal
binlog_rows_query_log_events = TRUE

[mysqldump]
quick
quote-names
max_allowed_packet      = 1024M

[mysql]
no-auto-rehash  # faster start of mysql but no tab completition

#[isamchk]
##key_buffer             = 16M

[myisamchk]
sort_buffer_size = 512M
read_buffer = 8M
write_buffer = 8M
key_buffer_size = 512M


#GTID
gtid-mode                = on
enforce-gtid-consistency = true
master-info-repository   = TABLE
relay-log-info-repository=TABLE
sync-master-info         = 1

**Comment by zskarman** [comment] 2017-06-27 08:50
Guys, do you need any other for found the solution?

**Comment by ganoze** [comment] 2017-07-13 07:33
Your issue should be fixed with the upcoming 3.0.9 version of Centreon Broker. In the 3.0.4 version of Centreon Broker we introduced prepared statements to store performance data. However performance regression showed that this was a wrong move. I restored the old multi-values insertion mechanism in commit bb2e5df2c8943307fc8282fbced303916477021d. This should solve your performance issues.

**Comment by jrouanne** [comment] 2017-08-28 15:36
Hi, 
I have exactly the same problem.

In waiting for 3.0.9 version of Centreon Broker, it's possible to downgrade in 3.0.3 version without meet any compatibility issues with last version of Centreon Engine and the latest version of others module ?

Thanks in advance.

**Comment by ganoze** [comment] 2017-08-29 11:37
@jrouanne I would not recommand downgrading. This might get you in serious troubles.

**Comment by Tomszy** [comment] 2017-08-29 14:40
When will 3.0.9 broker available in repo?

**Comment by ganoze** [comment] 2017-08-30 09:26
It is likely to be release within the next two or three weeks. The first testing version is already available in our repository (http://yum.centreon.com/standard/3.4/el6/testing/x86_64/RPMS/)

**Closed** 2017-10-05 11:52 UTC
Labels: Kind/Bug, Status/Implemented
